const NCAA_LOGO_BASE = 'https://a.espncdn.com/i/teamlogos/ncaa/500';

const COLLEGE_ESPN_IDS = {
  'air force': '2005',
  akron: '2006',
  alabama: '333',
  appalachianstate: '2026',
  arizona: '12',
  'arizona state': '9',
  arkansas: '8',
  army: '349',
  auburn: '2',
  baylor: '239',
  boise: '68',
  'boise state': '68',
  bostoncollege: '103',
  'boston college': '103',
  bowlinggreen: '189',
  buffalo: '2084',
  byu: '252',
  california: '25',
  cal: '25',
  charlotte: '2429',
  cincinnati: '2132',
  clemson: '228',
  coastalcarolina: '324',
  'coastal carolina': '324',
  colorado: '38',
  coloradostate: '36',
  'colorado state': '36',
  duke: '150',
  easternmichigan: '2199',
  'eastern michigan': '2199',
  florida: '57',
  'florida state': '52',
  fresno: '278',
  'fresno state': '278',
  georgia: '61',
  'georgia state': '2247',
  'georgia tech': '59',
  houston: '248',
  illinois: '356',
  indiana: '84',
  iowa: '2294',
  'iowa state': '66',
  jacksonstate: '2296',
  'jackson state': '2296',
  jamesmadison: '256',
  'james madison': '256',
  kansas: '2305',
  'kansas state': '2306',
  kentucky: '96',
  liberty: '2335',
  louisville: '97',
  lsu: '99',
  marshall: '276',
  memphis: '235',
  miami: '2390',
  'miami fl': '2390',
  'miami florida': '2390',
  michigan: '130',
  'michigan state': '127',
  minnesota: '135',
  mississippi: '145',
  'mississippi state': '344',
  missouri: '142',
  navy: '2426',
  nebraska: '158',
  'new mexico': '167',
  'nc state': '152',
  northwestern: '77',
  notredame: '87',
  'notre dame': '87',
  ohio: '195',
  'ohio state': '194',
  oklahoma: '201',
  'oklahoma state': '197',
  olemiss: '145',
  'ole miss': '145',
  oregon: '2483',
  'oregon state': '204',
  pennstate: '213',
  'penn state': '213',
  pittsburgh: '221',
  pitt: '221',
  purdue: '2509',
  rutgers: '164',
  smu: '2567',
  'san diego state': '21',
  southalabama: '6',
  'south alabama': '6',
  southcarolina: '2579',
  'south carolina': '2579',
  stanford: '24',
  syracuse: '183',
  tcu: '2628',
  temple: '218',
  tennessee: '2633',
  texas: '251',
  'texas a&m': '245',
  'texas a and m': '245',
  texasam: '245',
  texasaandm: '245',
  'texas tech': '2641',
  toledo: '2649',
  tulane: '2655',
  ucf: '2116',
  ucla: '26',
  uconn: '41',
  usc: '30',
  utah: '254',
  utsa: '2636',
  vanderbilt: '238',
  virginia: '258',
  'virginia tech': '259',
  wakeforest: '154',
  'wake forest': '154',
  washington: '264',
  washingtonstate: '265',
  'washington state': '265',
  wisconsin: '275',
  wyoming: '2751',
};

const NFL_LOGO_IDS = {
  ari: 'ARI',
  atl: 'ATL',
  bal: 'BAL',
  buf: 'BUF',
  car: 'CAR',
  chi: 'CHI',
  cin: 'CIN',
  cle: 'CLE',
  dal: 'DAL',
  den: 'DEN',
  det: 'DET',
  gb: 'GB',
  hou: 'HOU',
  ind: 'IND',
  jax: 'JAX',
  kc: 'KC',
  la: 'LAR',
  lar: 'LAR',
  lac: 'LAC',
  lv: 'LV',
  mia: 'MIA',
  min: 'MIN',
  ne: 'NE',
  no: 'NO',
  nyg: 'NYG',
  nyj: 'NYJ',
  phi: 'PHI',
  pit: 'PIT',
  sea: 'SEA',
  sf: 'SF',
  tb: 'TB',
  ten: 'TEN',
  wsh: 'WSH',
  was: 'WSH',
};

// Fallback lookup by full NFL team name (e.g. "Kansas City Chiefs") for call sites
// that only have the display name available.
const NFL_LOGO_BY_NAME = {
  'arizona cardinals': 'ARI',
  'atlanta falcons': 'ATL',
  'baltimore ravens': 'BAL',
  'buffalo bills': 'BUF',
  'carolina panthers': 'CAR',
  'chicago bears': 'CHI',
  'cincinnati bengals': 'CIN',
  'cleveland browns': 'CLE',
  'dallas cowboys': 'DAL',
  'denver broncos': 'DEN',
  'detroit lions': 'DET',
  'green bay packers': 'GB',
  'houston texans': 'HOU',
  'indianapolis colts': 'IND',
  'jacksonville jaguars': 'JAX',
  'kansas city chiefs': 'KC',
  'las vegas raiders': 'LV',
  'los angeles chargers': 'LAC',
  'los angeles rams': 'LAR',
  'miami dolphins': 'MIA',
  'minnesota vikings': 'MIN',
  'new england patriots': 'NE',
  'new orleans saints': 'NO',
  'new york giants': 'NYG',
  'new york jets': 'NYJ',
  'philadelphia eagles': 'PHI',
  'pittsburgh steelers': 'PIT',
  'san francisco 49ers': 'SF',
  'seattle seahawks': 'SEA',
  'tampa bay buccaneers': 'TB',
  'tennessee titans': 'TEN',
  'washington commanders': 'WSH',
};

function normalizeTeamName(name) {
  return String(name ?? '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

export function collegeLogoUrl(college) {
  const normalized = normalizeTeamName(college);
  const compact = normalized.replace(/\s+/g, '');
  const id = COLLEGE_ESPN_IDS[normalized] ?? COLLEGE_ESPN_IDS[compact];
  return id ? `${NCAA_LOGO_BASE}/${id}.png` : null;
}

export function nflLogoUrl(teamIdOrName) {
  const key = String(teamIdOrName ?? '').trim().toLowerCase();
  if (!key) return null;
  const id = NFL_LOGO_IDS[key] ?? NFL_LOGO_BY_NAME[key];
  return id ? `/logos/${id}.png` : null;
}

export function teamInitials(name) {
  const words = normalizeTeamName(name).split(' ').filter(Boolean);
  if (!words.length) return '--';
  return words.slice(0, 2).map(word => word[0]).join('').toUpperCase();
}
